excluded:
  - Pods

disabled_rules:
  - trailing_whitespace
  - line_length
  - multiple_closures_with_trailing_closure
  - notification_center_detachment

identifier_name:
  excluded: id

type_name:
  excluded: T
